name: Deploy on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Connect to VPS and deploy
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22

          script: |
            cd /home/cb/projects/youthcongress/api || exit 1            
            docker build -t youthcongressapi .
            docker stop youthcongressapi || true
            docker rm youthcongressapi || true
            docker run -d --name api.youthcongressnepal.org -p 8010:8010 youthcongressapi